drop table E2E.PAYMENTINFO;
drop table E2E.ORDERS;
drop table E2E.ADDRESSES;
drop table E2E.BILLINGINFO;
drop table E2E.ORDER_ITEMS;
drop table E2E.SHIPPINGINFO;

CREATE TABLE E2E.PAYMENTINFO ( 
  FIRST_NAME VARCHAR2(255) NOT NULL , 
  LAST_NAME VARCHAR2(255) NOT NULL , 
  PAYMENT_TYPE INTEGER , 
  CARD_NUM VARCHAR2(255) NOT NULL , 
  EXPIRE_DATE TIMESTAMP NOT NULL, 
  CARD_NAME VARCHAR2(255) , 
  DAILY_LIMIT FLOAT , 
  CURRENT_LIMT FLOAT );

ALTER TABLE E2E.PAYMENTINFO ADD CONSTRAINT "PAYMENTINFO_PK" PRIMARY KEY ( "CARD_NUM" );
  
CREATE TABLE E2E.ORDERS ( 
  "ORDER_NUMBER" INTEGER NOT NULL, 
  "SESSIONID" VARCHAR(255) , 
  "ORDER_DATE" TIMESTAMP , 
  "TOTAL_AMOUNT" FLOAT , 
  "EMAIL" VARCHAR(255) , 
  "STATUS" VARCHAR(255) );
  
CREATE TABLE E2E.ADDRESSES ( 
  "ADDRESS_ID" INTEGER NOT NULL, 
  "FIRST_NAME" VARCHAR(255) , 
  "LAST_NAME" VARCHAR(255) , 
  "ADDRESS_LINE1" VARCHAR(255) , 
  "ADDRESS_LINE2" VARCHAR(255) , 
  "CITY" VARCHAR(255),
  "STATE" VARCHAR(255),
  "ZIP_CODE" VARCHAR(255),
  "PHONE" VARCHAR(255)   
  );
  
CREATE TABLE E2E.BILLINGINFO (
  "BILLING_ID" INTEGER NOT NULL,
  "ORDER_ID" INTEGER,
  "CARDPAYMENTTYPE" INTEGER,
  "CARDNUM" VARCHAR(255),
  "EXPIREDATE" VARCHAR(255),
  "CARDNAME" VARCHAR(255),
  "ADDRESS_ID" INTEGER,
  "AUTHORIZATIONDATE" TIMESTAMP
);

CREATE TABLE E2E.ORDER_ITEMS (
  "ITEM_ID" INTEGER NOT NULL,
  "ORDER_ID" INTEGER,
  "SKU" VARCHAR(255),
  "QUANTITY" INTEGER,
  "UNITPRICE" FLOAT,
  "BRAND" VARCHAR(255),
  "MODEL" VARCHAR(255),
  "CATEGORY_ID" INTEGER,
  "DESCRIPTION" VARCHAR(255)
);

CREATE TABLE E2E.SHIPPINGINFO (
  "SHIPPING_ID" INTEGER NOT NULL,
  "ORDER_ID" INTEGER,
  "ADDRESS_ID" INTEGER,
  "SHIPPING_PROVIDER_ID" INTEGER,
  "SHIPMETHOD" INTEGER,
  "SHIPSPEED" VARCHAR(255)
);

show tables;