connect("weblogic", "welcome1", "t3://localhost:7101")
cd('/')
edit()
startEdit()
cd('/AppDeployments/CoherenceAdapter')
set('Targets',jarray.array([ObjectName('com.bea:Name=DefaultServer,Type=Server')], ObjectName))
cd('/AppDeployments/UMSAdapter')
set('Targets',jarray.array([ObjectName('com.bea:Name=DefaultServer,Type=Server')], ObjectName))
save()
activate() 