<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/PaymentInformations"
                xmlns:ns0="http://www.oracle.com/soasample"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns1 ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:tns="http://www.oracle.com/ValidatePayment"
                xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:f="http://www.example.org/faults">
  <oracle-xsl-mapper:schema xml:id="id_2">
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources xml:id="id_3">
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
        <oracle-xsl-mapper:schema location="../WSDLs/ValidatePayment.wsdl" xml:id="id_5"/>
        <oracle-xsl-mapper:rootElement name="PaymentInfo" namespace="http://www.oracle.com/soasample" xml:id="id_6"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_7">
        <oracle-xsl-mapper:schema location="../WSDLs/ValidatePaymentWrapper.wsdl" xml:id="id_8"/>
        <oracle-xsl-mapper:rootElement name="PaymentinfoCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PaymentInformations"
                                       xml:id="id_9"/>
        <oracle-xsl-mapper:param name="InvokePaymentInformations_PaymentInformationsSelect_Output_Select.PaymentinfoCollection"
                                 xml:id="id_10"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets xml:id="id_11">
      <oracle-xsl-mapper:target type="WSDL" xml:id="id_12">
        <oracle-xsl-mapper:schema location="../WSDLs/ValidatePayment.wsdl" xml:id="id_13"/>
        <oracle-xsl-mapper:rootElement name="PaymentStatus" namespace="http://www.oracle.com/soasample" xml:id="id_14"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI DEC 12 11:14:59 CET 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="InvokePaymentInformations_PaymentInformationsSelect_Output_Select.PaymentinfoCollection"
             xml:id="id_15"/>
  <xsl:template match="/" xml:id="id_16">
    <ns0:PaymentStatus xml:id="id_17">
      <xsl:choose xml:id="id_18">
        <xsl:when
                  xml:id="id_19"
                  test="/ns0:PaymentInfo/ns0:ExpireDate = $InvokePaymentInformations_PaymentInformationsSelect_Output_Select.PaymentinfoCollection/ns1:PaymentinfoCollection/ns1:Paymentinfo/ns1:expireDate/text() and /ns0:PaymentInfo/ns0:AuthorizationAmount &lt;= $InvokePaymentInformations_PaymentInformationsSelect_Output_Select.PaymentinfoCollection/ns1:PaymentinfoCollection/ns1:Paymentinfo/ns1:currentLimt">
          <ns0:Status xml:id="id_20">Valid</ns0:Status>
        </xsl:when>
        <xsl:when test="/ns0:PaymentInfo/ns0:ExpireDate != $InvokePaymentInformations_PaymentInformationsSelect_Output_Select.PaymentinfoCollection/ns1:PaymentinfoCollection/ns1:Paymentinfo/ns1:expireDate/text()"
                  xml:id="id_23">
          <ns0:Status xml:id="id_24">Exipration date not corresponding
                                     (<xsl:value-of select="$InvokePaymentInformations_PaymentInformationsSelect_Output_Select.PaymentinfoCollection/ns1:PaymentinfoCollection/ns1:Paymentinfo/ns1:expireDate" />)</ns0:Status>
        </xsl:when>
        <xsl:when test="$InvokePaymentInformations_PaymentInformationsSelect_Output_Select.PaymentinfoCollection/ns1:PaymentinfoCollection/ns1:Paymentinfo/ns1:currentLimt &lt;= /ns0:PaymentInfo/ns0:AuthorizationAmount"
                  xml:id="id_25">
          <ns0:Status xml:id="id_26">Authorization for amount not provided, max <xsl:value-of select="$InvokePaymentInformations_PaymentInformationsSelect_Output_Select.PaymentinfoCollection/ns1:PaymentinfoCollection/ns1:Paymentinfo/ns1:currentLimt"/></ns0:Status>
        </xsl:when>
        <xsl:otherwise xml:id="id_21">
          <ns0:Status xml:id="id_22">Invalid</ns0:Status>
        </xsl:otherwise>
      </xsl:choose>
    </ns0:PaymentStatus>
  </xsl:template>
</xsl:stylesheet>
